### ISSUE TITLE
補充資源

### ISSUE THREAD

**Issue by eric999j** [leemengtaiwan/deep-learning-resources#5]
值得追蹤大佬之前剛好有整理，可以參考這個  
https://github.com/eric999j/Clutter/blob/master/1.1.4.%E5%B7%A5%E7%A8%8B-%E5%A4%A7%E4%BD%AC%E5%80%91.md  

另外還想推薦幾個網站
Arxiv-Sanity(搜集前沿國外論文的網站): http://www.arxiv-sanity.com  
Fast.ai(另一個大家狂推的課): https://course.fast.ai/  
CrashCourse(谷歌大大認證): https://developers.google.com/machine-learning/crash-course/ml-intro  

我有記在這邊
https://ithelp.ithome.com.tw/articles/10223667

**Comment by leemengtw** [comment]
Hi @eric999j 謝謝你的建議！ 最近會排時間做一波更新，到時候會連 #4 一起處理：）

**Comment by eric999j** [comment]
Hi leemeng,

不急不急，不過能幫上忙真是太好了😁

Sincerely,
Eric Lu

LeeMeng (李孟) <notifications@github.com> 於 2020年1月14日 週二 下午6:34 寫道：
